# Generated by Django 2.2.4 on 2020-10-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_exp', '0002_auto_20201020_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('gold', models.IntegerField()),
                ('score', models.IntegerField()),
                ('round_count', models.IntegerField()),
                ('defender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_exp.User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
